# TCL File Generated by Component Editor 13.1
# Fri Mar 11 11:26:18 GMT 2016
# DO NOT MODIFY


# 
# cordic "cordic" v1.0
#  2016.03.11.11:26:18
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module cordic
# 
set_module_property DESCRIPTION ""
set_module_property NAME cordic
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME cordic
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cordic
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file atan_pkg.vhd VHDL PATH ip/cordic/atan_pkg.vhd
add_fileset_file cordic.vhd VHDL PATH ip/cordic/cordic.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point hw_cos
# 
add_interface hw_cos nios_custom_instruction end
set_interface_property hw_cos clockCycle 0
set_interface_property hw_cos operands 2
set_interface_property hw_cos ENABLED true
set_interface_property hw_cos EXPORT_OF ""
set_interface_property hw_cos PORT_NAME_MAP ""
set_interface_property hw_cos CMSIS_SVD_VARIABLES ""
set_interface_property hw_cos SVD_ADDRESS_GROUP ""

add_interface_port hw_cos clk clk Input 1
add_interface_port hw_cos start start Input 1
add_interface_port hw_cos reset reset Input 1
add_interface_port hw_cos done done Output 1
add_interface_port hw_cos angle dataa Input 32
add_interface_port hw_cos cos result Output 32

